version: '2'
services:
    hiptodo-app:
        image: hiptodo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hiptodo-postgresql:5432/HipToDo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hiptodo-postgresql:
        extends:
            file: postgresql.yml
            service: hiptodo-postgresql
